# flash with: esphome run smartvelux.yaml
# baseline created with: esphome wizard smartvelux.yaml

esphome:
  name: veluxremote

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

# source secrets.yaml file wiht 2 top elements: wifi_ssid and wifi_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


output:
  - platform: gpio
    id: pin_open
    pin:
      number: GPIO25
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
  - platform: gpio
    id: pin_stop
    pin:
      number: GPIO26
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
  - platform: gpio
    id: pin_close
    pin:
      number: GPIO27
      mode: OUTPUT_OPEN_DRAIN
      inverted: true

button:
  - platform: template
    name: "Auf"
    icon: mdi:arrow-up-bold-circle
    on_press:
      - output.turn_on: pin_open
      - delay: 300ms
      - output.turn_off: pin_open
  - platform: template
    name: "Stop"
    icon: mdi:stop-circle
    on_press:
      - output.turn_on: pin_stop
      - delay: 300ms
      - output.turn_off: pin_stop
  - platform: template
    name: "Zu"
    icon: mdi:arrow-down-bold-circle
    on_press:
      - output.turn_on: pin_close
      - delay: 300ms
      - output.turn_off: pin_close